# Generated by Django 2.1.7 on 2019-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viyaan_app', '0002_auto_20190506_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_picture',
            field=models.ImageField(blank=True, default=12, upload_to='images/'),
            preserve_default=False,
        ),
    ]
