# Generated by Django 2.1.7 on 2019-05-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viyaan_app', '0003_auto_20190506_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
