# Generated by Django 2.1.7 on 2019-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=512, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=512, null=True)),
                ('course_contents', models.TextField(blank=True, max_length=512, null=True)),
                ('course_cost', models.FloatField(default=0, null=True)),
                ('modefied_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_link', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('discription', models.CharField(blank=True, max_length=512, null=True)),
                ('photo', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtubeplayerlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('urls', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
